config/routes.rb
Rails.application.routes.draw do
  get 'users/search'
  post 'users/search'

  post 'users/result'

end

app/models/user.rb
# require 'httparty'
class User
  attr_reader :user
  def initialize(username)
    @user = get_response(username)
  end

  def get_response(username)
    @response = HTTParty.get("https://api.github.com/users/#{username}/repos")
  end

  def get_repo_name(position)
    @user[position][:name]
  end

  def get_repo_url(position)
    @user[position][:url]
  end

  def get_repo_description(position)
    @user[position][:description]
  end

  def get_updated_time(position)
    @user[position][:updated_at] - time.now
  end




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def search
    # @search = User.new(name: params[:name])
  end

  def result
    @result = User.new(params[:username])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GithubProfile</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/result.html.erb
<%= @result %>

<p><%= @result.user[0]["home_url"]%></p>

<%= link_to "#{@result.user[0]["name"]}", @result.user[0]["home_url"]%>


<!-- "#{@result.get_repo_name(1)}", @result.get_repo_url(1) -->

app/views/users/search.html.erb
<h1>Repocat</h1>
<p>Enter a username to find his or her repository on github:</p>

<p> Show Path: <%= users_search_path %></p>
<p> Show URL: <%= users_search_url %></p>

<%= form_tag users_result_path do %>
<%= text_field_tag :username %>
<%= button_tag "Get User's Repository"%>

<% end %>

<!-- <form method="post" action="search">
  <p>
    <label for="username">Username:</label>
    <input type="text" id="username" placeholder="username" name="username"> </input>
  </p> -->